version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: ["./wait-for-it.sh", "database:5432", "--", "yarn", "run:server"]
    volumes:
      - /usr/src/app
    environment:
      DATABASE: postgres
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      HOSTNAME: ${HOSTNAME}
      PORT: ${PORT}
      SUPER_ADMIN_USER_IDENTIFIER: ${SUPER_ADMIN_USER_IDENTIFIER}
      SUPER_ADMIN_USER_PASSWORD: ${SUPER_ADMIN_USER_PASSWORD}
    depends_on:
      - database
      - worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "database:5432", "--", "yarn", "run:worker"]
    volumes:
      - /usr/src/app
    environment:
      DATABASE: postgres
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      NODE_ENV: ${NODE_ENV}
      HOSTNAME: ${HOSTNAME}
      PORT: ${PORT}
      EMAIL: ${EMAIL}
      SUPER_ADMIN_USER_IDENTIFIER: ${SUPER_ADMIN_USER_IDENTIFIER}
      SUPER_ADMIN_USER_PASSWORD: ${SUPER_ADMIN_USER_PASSWORD}
    depends_on:
      - database
  database:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendure