version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: ["yarn", "run:server"]
    volumes:
      - /usr/src/app
    environment:
      DATABASE: sqlite
      NODE_ENV: ${NODE_ENV}
      HOSTNAME: ${HOSTNAME}
      PORT: ${PORT}
      EMAIL: ${EMAIL}
      SUPER_ADMIN_USER_IDENTIFIER: ${SUPER_ADMIN_USER_IDENTIFIER}
      SUPER_ADMIN_USER_PASSWORD: ${SUPER_ADMIN_USER_PASSWORD}
    depends_on:
      - worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "run:worker"]
    volumes:
      - /usr/src/app
    environment:
      DATABASE: sqlite
      NODE_ENV: ${NODE_ENV}
      HOSTNAME: ${HOSTNAME}
      PORT: ${PORT}
      EMAIL: ${EMAIL}
      SUPER_ADMIN_USER_IDENTIFIER: ${SUPER_ADMIN_USER_IDENTIFIER}
      SUPER_ADMIN_USER_PASSWORD: ${SUPER_ADMIN_USER_PASSWORD}